clear all;
Meta.instance.readA;
Meta.instance.readPCA;

global handle shapeParam poseParam body texts
shapeParam = Meta.instance.sem_default;
poseParam = repmat(eye(3), [1 1 15]);
tmpBody = Body(poseParam, shapeParam);
texts = cell(1,Meta.instance.sem_num);

initFigure;
body = Body(poseParam, shapeParam);
handle = trisurf(Meta.instance.triangles, ...
    body.points(:,1), ...
    body.points(:,2), ...
    body.points(:,3), ...
    'LineStyle','none', ...
    'FaceLighting','phong', ...
    'CData', Meta.instance.trisurfCData ...
);

for i=1 : Meta.instance.sem_num
    y = 20*Meta.instance.sem_num - i*20;
    uicontrol('Style','text',...
        'Position',[10 y 100 20],...
        'String', Meta.instance.sem_label{i});
    texts{i} = uicontrol('Style','text',...
        'Position',[128 y 100 20],...
        'String', num2str(shapeParam(i)));
    uicontrol('Style', 'slider',...
    'Min', 0,'Max', 1,'Value',shapeParam(i),...
    'Position', [256 y 512 20],...
    'Callback', {@callback,1,i});
end

tmpBody.drawMesh(1.5);
